Lambda interpreter
zzzloba/SPBU_Homework_sem4 pull request #13
Opened 2020-03-14 11:01 UTC by zzzloba

2020-04-15 09:38 UTC, yurii-litvinov requested changes

2020-04-15 09:38 UTC, yurii-litvinov commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +// Type describing lambda term
Комментарии лучше в XML Documentation, с ///

2020-04-15 09:38 UTC, yurii-litvinov commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +            |Variable name ->
Везде были пробелы после `|`, а тут нет, нехорошо

2020-04-15 09:38 UTC, yurii-litvinov commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +    | _ -> invalidArg "expression" "Error: expression is not a beta redex"
Нее, самый внешний терм не обязан быть редэксом, но где-то внутри редэксы вполне могут быть

2020-04-15 09:38 UTC, yurii-litvinov commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +    | _ -> invalidArg "expression" "Error: expression is not a beta redex"
К тому же в результате редукции может появиться редэкс (как в примере с расходящимся комбинатором), да и внутри могут быть редэксы опять же, так что одной подстановки недостаточно. У Вас получилась не бета-редукция, а бета-преобразование.

2020-06-03 08:55 UTC, zzzloba commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +            |Variable name ->
> Везде были пробелы после `|`, а тут нет, нехорошо

Поправил

2020-06-03 08:55 UTC, zzzloba commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +    | _ -> invalidArg "expression" "Error: expression is not a beta redex"
> К тому же в результате редукции может появиться редэкс (как в примере с расходящимся комбинатором), да и внутри могут быть редэксы опять же, так что одной подстановки недостаточно. У Вас получилась не бета-редукция, а бета-преобразование.

Косяк, поменял, должна быть бета-редукция теперь

2020-06-03 08:55 UTC, zzzloba commented on Lab3/Task3/LambdaInterpreter/Interpreter.fs
> +// Type describing lambda term
> Комментарии лучше в XML Documentation, с ///

Поправил

2020-06-04 13:12 UTC, yurii-litvinov approved these changes
Да, теперь всё хорошо, зачтена

2020-06-04 13:12 UTC, yurii-litvinov commented on appveyor.yml
> -  - solution_path: Test\PriorityQueue\PriorityQueue.sln
Этот пуллреквест в случае мерджа удалит из мастера CI для всех остальных задач, так и задумывалось?

2020-06-04 13:34 UTC, zzzloba commented on appveyor.yml
> -  - solution_path: Test\PriorityQueue\PriorityQueue.sln
> Этот пуллреквест в случае мерджа удалит из мастера CI для всех остальных задач, так и задумывалось?

Чтобы собиралось и тестировалось на appveyor шустрее, пока висит пуллреквест, оставил только текущее решение для тестирования, как-то костыльно получилось (мягко говоря). Он для каждого решения после сборки запускает вообще все обнаруженные тесты, поэтому каждый коммит долговато поверялся, косяк, не понял пока, как по-человечески это сделать 🤔

2020-06-04 13:52 UTC, yurii-litvinov commented on appveyor.yml
> -  - solution_path: Test\PriorityQueue\PriorityQueue.sln
Обычно не парятся и дают AppVeyor-у поработать. Ну, точнее, в реальной жизни каждый проект в своём репозитории, так что это не проблема.

2020-06-05 08:33 UTC, merged