Bracket balance checker
zzzloba/SPBU_Homework_sem4 pull request #14
Opened 2020-03-19 13:30 UTC by zzzloba

2020-04-16 15:51 UTC, yurii-litvinov requested changes

2020-04-16 15:51 UTC, yurii-litvinov commented on Lab4/Task1/BracketBalance/BracketBalance/Source/Utils/Stack.fs
> +type CharStack =
Стек реализовывать было вовсе не обязательно, обычный 'a list бы прекрасно справился

2020-04-16 15:51 UTC, yurii-litvinov commented on Lab4/Task1/BracketBalance/BracketBalance/Source/Utils/Stack.fs
> +// Implements immutable stack
Комментарии лучше в формате XML Documentation

2020-04-16 15:51 UTC, yurii-litvinov commented on Lab4/Task1/BracketBalance/BracketBalance/Source/BracketChecker.fs
> +            if (equals h opening) then
Неее, скобки могут быть трёх видов по условию --- в одном выражении. Например, "[()]" должно считаться корректной скобочной последовательностью, "([)]" --- нет

2020-06-03 08:56 UTC, zzzloba commented on Lab4/Task1/BracketBalance/BracketBalance/Source/Utils/Stack.fs
> +// Implements immutable stack
> Комментарии лучше в формате XML Documentation

Поправил

2020-06-03 08:56 UTC, zzzloba commented on Lab4/Task1/BracketBalance/BracketBalance/Source/Utils/Stack.fs
> +type CharStack =
> Стек реализовывать было вовсе не обязательно, обычный 'a list бы прекрасно справился

Да, действительно делать стек было бредом каким-то, переделал :)

2020-06-03 08:56 UTC, zzzloba commented on Lab4/Task1/BracketBalance/BracketBalance/Source/BracketChecker.fs
> +            if (equals h opening) then
> Неее, скобки могут быть трёх видов по условию --- в одном выражении. Например, "[()]" должно считаться корректной скобочной последовательностью, "([)]" --- нет

Переделал, теперь в функцию передаются возможные пары "открывающая-закрывыющая скобки", по ним проверяется баланс

2020-06-04 13:29 UTC, yurii-litvinov approved these changes
Да, всё ок, зачтена

2020-06-04 13:29 UTC, yurii-litvinov commented on Lab4/Task1/BracketBalance.Tests/BracketBalanceTest.fs
> +        yield (checkGeneric ([('<', '>')]), convertExpression '<' '>' expression, expected)
Думаете, что если для `()` всё работает, то для `<>` может сломаться? :)

2020-06-04 13:29 UTC, yurii-litvinov commented on Lab4/Task1/BracketBalance/BracketBalance/Source/BracketChecker.fs
> +        bracketPairs |> List.contains (left, right)
Хитро, но я бы в Map их сложил

2020-06-06 09:21 UTC, merged