Workflow for calculating and rounding floats
zzzloba/SPBU_Homework_sem4 pull request #17
Opened 2020-03-31 08:13 UTC by zzzloba

2020-04-18 10:19 UTC, yurii-litvinov requested changes
Надо немного поправить

2020-04-18 10:19 UTC, yurii-litvinov commented on Lab6/Task1/WorkflowCalculator/Calculator.fs
> +         match f x with
Что-то тут отступ в пять пробелов

2020-04-18 10:19 UTC, yurii-litvinov commented on Lab6/Task1/WorkflowCalculator/Calculator.fs
> +        x
Не-а, тут тоже надо округлять, иначе получится, что если сразу делается return, то получается точное значение.

2020-04-18 10:19 UTC, yurii-litvinov commented on Lab6/Task1/WorkflowCalculator/Calculator.fs
> +         match f x with
А зачем match? Из одной альтернативы?

2020-06-03 09:01 UTC, zzzloba commented on Lab6/Task1/WorkflowCalculator/Calculator.fs
> +         match f x with
> Что-то тут отступ в пять пробелов

Поправил

2020-06-03 09:01 UTC, zzzloba commented on Lab6/Task1/WorkflowCalculator/Calculator.fs
> +        x
> Не-а, тут тоже надо округлять, иначе получится, что если сразу делается return, то получается точное значение.

Косяк, теперь округляется

2020-06-03 09:01 UTC, zzzloba commented on Lab6/Task1/WorkflowCalculator/Calculator.fs
> +         match f x with
> А зачем match? Из одной альтернативы?

Если правильно помню, хотел так избавиться от явного указания типов параметров, но не знаю, почему решил, что это адекватное решение :))
Убрал этот match

2020-06-04 15:32 UTC, yurii-litvinov approved these changes
Всё отлично, зачтена

2020-06-06 09:23 UTC, merged